import abc
import json

class BaseModel(abc.ABC):
    """
    Abstract base class for Large Language Models (LLMs).
    Defines the common interface for generating stock analysis.
    """

    def __init__(self, config: dict):
        """
        Initializes the base model.

        Args:
            config (dict): Configuration specific to the LLM model.
                           May include API keys, model names, endpoints, etc.
        """
        self.config = config

    @abc.abstractmethod
    def generate_analysis(self, prompt: str, image_path: str = None) -> str:
        """
        Generates stock analysis based on the provided prompt.

        Args:
            prompt (str): The complete prompt including instructions and stock data.
            image_path (str, optional): Path to chart image to include in analysis.
                                       May be ignored by models that don't support images.

        Returns:
            str: The analysis generated by the LLM.

        Raises:
            NotImplementedError: If the method is not implemented by the subclass.
            Exception: For any errors during API calls or processing.
        """
        raise NotImplementedError

    def _format_stock_data_for_prompt(self, stock_data: dict) -> str:
        """
        Formats the stock data dictionary into a JSON string for prompt injection.
        Handles potential non-serializable data if necessary in the future.

        Args:
            stock_data (dict): The dictionary containing stock information.

        Returns:
            str: A JSON string representation of the stock data.
        """
        try:
            # Simple JSON dump for now, can add more complex handling if needed
            return json.dumps(stock_data, indent=2)
        except TypeError as e:
            print(f"Error serializing stock data: {e}")
            # Fallback or specific handling for non-serializable types if encountered
            return "{}" # Return empty JSON object on error

    def load_prompt_template(self, prompt_file_path: str) -> str:
        """
        Loads the prompt template from a file.

        Args:
            prompt_file_path (str): The path to the prompt template file.

        Returns:
            str: The content of the prompt template file.

        Raises:
            FileNotFoundError: If the prompt file cannot be found.
            IOError: For other reading errors.
        """
        try:
            with open(prompt_file_path, 'r', encoding='utf-8') as f:
                return f.read()
        except FileNotFoundError:
            print(f"Error: Prompt template file not found at {prompt_file_path}")
            raise
        except IOError as e:
            print(f"Error reading prompt template file {prompt_file_path}: {e}")
            raise

    def construct_prompt(self, prompt_template: str, stock_data: dict) -> str:
        """
        Constructs the final prompt by injecting stock data into the template.

        Args:
            prompt_template (str): The prompt template string.
            stock_data (dict): The dictionary containing stock information.

        Returns:
            str: The final prompt ready to be sent to the LLM.
        """
        formatted_data = self._format_stock_data_for_prompt(stock_data)
        # Replace the placeholder in the template
        final_prompt = prompt_template.replace("{stock_data_placeholder}", formatted_data)
        return final_prompt
