import os
from openai import OpenAI
from .basemodel import BaseModel
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class DeepSeekR1Model(BaseModel):
    """
    Implementation for the DeepSeek R1 model accessed via a local
    OpenAI-compatible server (like LM Studio).
    """

    def __init__(self, config: dict):
        """
        Initializes the DeepSeek R1 model client.

        Args:
            config (dict): Configuration specific to the LLM model.
                           Expected to contain the model name.
                           The base_url for the local server is assumed.
        """
        super().__init__(config)
        # LM Studio default endpoint
        # TODO: Consider making the base_url configurable in config.json
        self.base_url = os.environ.get("LMSTUDIO_API_BASE", "http://localhost:1234/v1")
        self.model_name = config.get("name", "deepseek-r1-distill-qwen-7b") # Default if not in specific config

        try:
            # Point OpenAI client to the local server
            # API key is not required for local LM Studio server
            self.client = OpenAI(base_url=self.base_url, api_key="not-needed")
            logging.info(f"Initialized DeepSeekR1Model client for model '{self.model_name}' at {self.base_url}")
            # Optional: Add a check here to see if the server is reachable
            # self.client.models.list()
        except Exception as e:
            logging.error(f"Failed to initialize OpenAI client for DeepSeekR1Model: {e}")
            self.client = None # Ensure client is None if initialization fails

    def generate_analysis(self, prompt: str) -> str:
        """
        Generates stock analysis using the locally hosted DeepSeek R1 model.

        Args:
            prompt (str): The complete prompt including instructions and stock data.

        Returns:
            str: The analysis generated by the LLM. Returns an error message string
                 if generation fails.
        """
        if not self.client:
            error_msg = "DeepSeekR1Model client not initialized. Cannot generate analysis."
            logging.error(error_msg)
            return error_msg

        try:
            logging.info(f"Sending request to DeepSeek model '{self.model_name}'...")
            # Note: LM Studio uses the model loaded in the UI, the 'model' param might be ignored
            # depending on server configuration, but we include it for compatibility.
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7, # Adjust temperature as needed for creativity vs consistency
                # max_tokens=1024 # Optional: Limit response length
            )
            logging.info("Received response from DeepSeek model.")

            if response.choices and response.choices[0].message:
                analysis = response.choices[0].message.content.strip()
                # Optional: Add post-processing to clean up the response if needed
                return analysis
            else:
                logging.warning("Received empty response from DeepSeek model.")
                return "Error: Received empty response from the model."

        except Exception as e:
            logging.error(f"Error during DeepSeek model API call: {e}")
            # Consider more specific error handling based on potential OpenAI exceptions
            return f"Error generating analysis: {e}"

# Example usage (for testing purposes)
if __name__ == '__main__':
    # Mock config and data for testing
    mock_config = {"name": "deepseek-r1-distill-qwen-7b"}
    mock_stock_data = {
        "Ticker": "TEST",
        "CompanyName": "Test Inc.",
        "Price": 100.00,
        "ChangePercent": 5.0,
        "Volume": 1000000,
        "MarketCap": "1B",
        "RSI": 60,
        "SMA20": 95.0,
        "VWAP": 98.0,
        "Pivot_S1": 90.0,
        "Pivot_R1": 110.0,
        "News": [{"title": "Test Inc. announces new product", "summary": "Positive outlook."}]
    }

    # Assume llm_prompt.md exists in the parent directory relative to this script
    # Adjust path as necessary depending on execution context
    prompt_path = os.path.join(os.path.dirname(__file__), '..', 'llm_prompt.md')

    model = DeepSeekR1Model(mock_config)

    if model.client: # Check if client initialized successfully
        try:
            template = model.load_prompt_template(prompt_path)
            final_prompt = model.construct_prompt(template, mock_stock_data)
            print("--- Constructed Prompt ---")
            print(final_prompt)
            print("\n--- Generating Analysis ---")
            analysis_result = model.generate_analysis(final_prompt)
            print("\n--- Analysis Result ---")
            print(analysis_result)
        except FileNotFoundError:
            print(f"Test failed: Prompt file not found at {prompt_path}")
        except Exception as e:
            print(f"An error occurred during testing: {e}")
    else:
        print("Test failed: Model client could not be initialized.")
