import os
import json
import logging
from openai import OpenAI
from typing import Dict

from .basemodel import BaseModel
from ..tools import search_internet  # Import the tool function

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class GPTUnified(BaseModel):
    """
    Unified implementation for the OpenAI GPT model using the official API.
    Handles agentic tool calling for internet search.
    """

    def __init__(self, config: dict):
        """
        Initializes the GPT model client.

        Args:
            config (dict): Configuration specific to the LLM model.
                           Expected to contain 'name'.
                           Requires OPENAI_API_KEY environment variable to be set.
        """
        super().__init__(config)
        self.model_name = config.get("name", "gpt-4o-mini")  # Default to gpt-4o if not specified
        self.client = None
        self.api_key = config.get("api_key")  # Get key from config first

        if not self.api_key:
            # Fallback to environment variable if not in config
            self.api_key = os.getenv("OPENAI_API_KEY")

        if not self.api_key:
            logging.error("OpenAI API key not found in config or OPENAI_API_KEY environment variable.")
        else:
            try:
                # Pass the API key explicitly
                self.client = OpenAI(api_key=self.api_key)
                # Verify connection (optional, but good practice)
                self.client.models.list()
                logging.info(f"Initialized GPTUnified client for model '{self.model_name}'")
            except Exception as e:
                logging.error(f"Failed to initialize OpenAI client for GPTUnified: {e}.", exc_info=True)
                self.client = None

        # Define the tool schema for the OpenAI API
        self.tools = [
            {
                "type": "function",
                "function": {
                    "name": "search_internet",
                    "description": "Search the internet for recent news or information about a given query, typically a stock ticker or company name.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "query": {
                                "type": "string",
                                "description": "The search query (e.g., 'AAPL stock news', 'Microsoft recent announcements').",
                            },
                            "max_results": {
                                "type": "integer",
                                "description": "Maximum number of search results to return (default 3).",
                            }
                        },
                        "required": ["query"],
                    },
                },
            }
        ]
        self.available_tools = {
            "search_internet": search_internet,
        }

    def generate_analysis(self, prompt: str, image_path: str = None) -> str:
        """
        Generates stock analysis using the GPT model, handling tool calls.

        Args:
            prompt (str): The complete initial user prompt.
            image_path (str, optional): Path to chart image to include in analysis.

        Returns:
            str: The analysis generated by the LLM. Returns an error message string
                 if generation fails.
        """
        if not self.client:
            error_msg = "GPTUnified client not initialized. Cannot generate analysis."
            logging.error(error_msg)
            return error_msg

        # Prepare the message content
        message_content = []
        
        # Add the text prompt
        message_content.append({"type": "text", "text": prompt})
        
        # Add the image if provided
        if image_path and os.path.exists(image_path):
            try:
                with open(image_path, "rb") as image_file:
                    # Convert image to base64
                    import base64
                    base64_image = base64.b64encode(image_file.read()).decode('utf-8')
                    
                    # Log the length of the base64 string
                    logging.info(f"Base64 image string length: {len(base64_image)}")

                    # Add image to message content with explicit detail level
                    message_content.append({
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{base64_image}"
                        }
                    })
                logging.info(f"Included chart image from {image_path} in analysis request with high detail")
            except Exception as e:
                logging.error(f"Error processing image {image_path}: {e}", exc_info=True)
        
        messages = [{"role": "user", "content": message_content}]
        max_tool_calls = 3  # Safety limit

        try:
            logging.info(f"Sending initial request to OpenAI model '{self.model_name}'...")
            for _ in range(max_tool_calls):
                response = self.client.chat.completions.create(
                    model=self.model_name,
                    messages=messages,
                    tools=self.tools,
                    tool_choice="auto",  # Let the model decide whether to use tools
                )
                response_message = response.choices[0].message
                tool_calls = response_message.tool_calls

                if not tool_calls:
                    # No tool call, this is the final response
                    logging.info("Model provided final analysis.")
                    return response_message.content.strip() if response_message.content else "Error: Received empty final response."

                # Process tool calls
                messages.append(response_message)  # Add assistant's message with tool_calls
                logging.info(f"Model requested tool call(s): {[tc.function.name for tc in tool_calls]}")

                for tool_call in tool_calls:
                    function_name = tool_call.function.name
                    function_to_call = self.available_tools.get(function_name)
                    if function_to_call:
                        try:
                            function_args = json.loads(tool_call.function.arguments)
                            logging.info(f"Executing tool '{function_name}' with args: {function_args}")
                            function_response = function_to_call(**function_args)
                            messages.append(
                                {
                                    "tool_call_id": tool_call.id,
                                    "role": "tool",
                                    "name": function_name,
                                    "content": json.dumps(function_response),  # Tool results need to be JSON string
                                }
                            )
                            logging.info(f"Appended tool '{function_name}' result to history.")
                        except Exception as e:
                            logging.error(f"Error executing tool '{function_name}': {e}", exc_info=True)
                            messages.append(
                                {
                                    "tool_call_id": tool_call.id,
                                    "role": "tool",
                                    "name": function_name,
                                    "content": json.dumps({"error": f"Failed to execute tool {function_name}: {str(e)}"}),
                                }
                            )
                    else:
                        logging.error(f"Model requested unknown tool: {function_name}")
                        messages.append(
                            {
                                "tool_call_id": tool_call.id,
                                "role": "tool",
                                "name": function_name,
                                "content": json.dumps({"error": f"Unknown tool requested: {function_name}"}),
                            }
                        )

                # Loop back to call the model again with the tool results
                logging.info("Sending updated history back to model after tool execution...")

            # If loop finishes, max_tool_calls was reached
            logging.warning(f"Maximum tool call limit ({max_tool_calls}) reached.")
            return "Error: Reached maximum tool call limit."

        except Exception as e:
            logging.error(f"Error during OpenAI API call: {e}", exc_info=True)
            return f"Error generating analysis: {e}"

# Example usage (for testing purposes - requires OPENAI_API_KEY)
if __name__ == '__main__':
    if not os.getenv("OPENAI_API_KEY"):
        print("Error: OPENAI_API_KEY environment variable not set.")
    else:
        mock_config = {"name": "gpt-4o-mini"}
        mock_stock_data = {
            "Ticker": "MSFT", "CompanyName": "Microsoft Corp.", "Price": 450.00,
            # Add other relevant mock data fields here...
            "News": []  # Start with empty news to encourage search
        }
        prompt_path = os.path.join(os.path.dirname(__file__), '..', 'llm_prompt.md')

        model = GPT4oMini(mock_config)

        if model.client:
            try:
                template = model.load_prompt_template(prompt_path)
                final_prompt = model.construct_prompt(template, mock_stock_data)
                print("--- Constructed Prompt (Snippet) ---")
                print(final_prompt[:500] + "...")  # Print snippet
                print("\n--- Generating Analysis (using GPT-4o-mini with potential tool use) ---")
                analysis_result = model.generate_analysis(final_prompt)
                print("\n--- Analysis Result ---")
                print(analysis_result)
            except FileNotFoundError:
                print(f"Test failed: Prompt file not found at {prompt_path}")
            except Exception as e:
                print(f"An error occurred during testing: {e}")
        else:
            print("Test failed: Model client could not be initialized (Check API key and connection).")
