import os
import ollama
from .basemodel import BaseModel
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class Llama3_2VisionModel(BaseModel):
    """
    Implementation for the Llama 3.2 Vision model accessed via the
    local Ollama server.
    """

    def __init__(self, config: dict):
        """
        Initializes the Llama 3.2 Vision model client using Ollama.

        Args:
            config (dict): Configuration specific to the LLM model.
                           Expected to contain 'name' and 'ollama_model_name'.
        """
        super().__init__(config)
        # Get the specific Ollama model name from config, default if necessary
        self.model_name = config.get("ollama_model_name", "llama3.2-vision")
        self.client = None # Initialize client as None

        try:
            # Initialize the Ollama client. It automatically connects to the default
            # Ollama server address (http://localhost:11434) unless OLLAMA_HOST is set.
            self.client = ollama.Client()
            # Verify connection and model availability
            self.client.list() # This will raise an exception if the server is not reachable
            logging.info(f"Initialized Llama3_2VisionModel client for model '{self.model_name}'")
            # You could add a check here to see if the specific model exists,
            # but ollama.chat will handle model not found errors.
        except Exception as e:
            logging.error(f"Failed to initialize Ollama client for Llama3_2VisionModel: {e}")
            self.client = None # Ensure client is None if initialization fails

    def generate_analysis(self, prompt: str, image_path: str = None) -> str:
        """
        Generates stock analysis using the locally hosted Llama 3.2 Vision model via Ollama.

        Args:
            prompt (str): The complete prompt including instructions and stock data.
            image_path (str, optional): Path to chart image to include in analysis.

        Returns:
            str: The analysis generated by the LLM. Returns an error message string
                 if generation fails.
        """
        if not self.client:
            error_msg = "Llama3_2VisionModel client not initialized. Cannot generate analysis."
            logging.error(error_msg)
            return error_msg

        try:
            logging.info(f"Sending request to Ollama model '{self.model_name}'...")

            # Create message with prompt and optional image
            messages = [{'role': 'user', 'content': prompt}]
            
            if image_path and os.path.exists(image_path):
                # Read image file and encode it
                with open(image_path, 'rb') as img_file:
                    image_bytes = img_file.read()
                
                # Add image to messages
                messages[0]['images'] = [image_bytes]
                logging.info(f"Included chart image from {image_path} in analysis request")

            # Send the request to the model
            response = self.client.chat(
                model=self.model_name,
                messages=messages
            )
            logging.info("Received response from Ollama model.")

            # Extract the content from the response
            if response and 'message' in response and 'content' in response['message']:
                analysis = response['message']['content'].strip()
                logging.info("Model provided analysis.")
                return analysis
            else:
                logging.warning(f"Received unexpected response format: {response}")
                return "Error: Received response in unexpected format."

        except ollama.ResponseError as e:
            logging.error(f"Ollama API Response Error: {e.status_code} - {e.error}")
            # Handle specific errors like model not found
            if "model not found" in str(e.error).lower():
                 return f"Error: Ollama model '{self.model_name}' not found. Make sure it's pulled."
            return f"Error generating analysis (Ollama API): {e.error}"
        except Exception as e:
            logging.error(f"Error during Ollama model API call: {e}")
            return f"Error generating analysis: {e}"

# Example usage (for testing purposes)
if __name__ == '__main__':
    # Mock config and data for testing
    mock_config = {"name": "llama-3.2-vision", "ollama_model_name": "llama3.2-vision"} # Use the actual name from config
    mock_stock_data = {
        "Ticker": "TEST",
        "CompanyName": "Test Inc.",
        "Price": 100.00,
        "ChangePercent": 5.0,
        "Volume": 1000000,
        "MarketCap": "1B",
        "RSI": 60,
        "SMA20": 95.0,
        "VWAP": 98.0,
        "Pivot_S1": 90.0,
        "Pivot_R1": 110.0,
        "News": [{"title": "Test Inc. announces new product", "summary": "Positive outlook."}]
    }

    # Assume llm_prompt.md exists in the parent directory relative to this script
    # Adjust path as necessary depending on execution context
    prompt_path = os.path.join(os.path.dirname(__file__), '..', 'llm_prompt.md')

    model = Llama3_2VisionModel(mock_config)

    if model.client: # Check if client initialized successfully
        try:
            template = model.load_prompt_template(prompt_path)
            final_prompt = model.construct_prompt(template, mock_stock_data)
            print("--- Constructed Prompt ---")
            print(final_prompt)
            print("\n--- Generating Analysis ---")
            analysis_result = model.generate_analysis(final_prompt)
            print("\n--- Analysis Result ---")
            print(analysis_result)
        except FileNotFoundError:
            print(f"Test failed: Prompt file not found at {prompt_path}")
        except Exception as e:
            print(f"An error occurred during testing: {e}")
    else:
        print("Test failed: Model client could not be initialized.")
